//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccGroup()
        {
            this.Account = new HashSet<Account>();
        }
    
        public int AccgroupID { get; set; }
        public string Accgroupname { get; set; }
        public string Accgroupalias { get; set; }
        public string AccunderprimarygroupName { get; set; }
        public Nullable<double> Accgroupbalance { get; set; }
        public Nullable<int> Accunderprimarygroupid { get; set; }
        public Nullable<double> DebitAmount { get; set; }
        public Nullable<double> CreditAmount { get; set; }
        public Nullable<int> MainGroupID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Account { get; set; }
    }
}
