//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.JournalVoucherChild = new HashSet<JournalVoucherChild>();
            this.VoucherMaster = new HashSet<VoucherMaster>();
        }
    
        public int AccountID { get; set; }
        public string AccountName { get; set; }
        public string Alias { get; set; }
        public string Print_Name { get; set; }
        public int LedgerTypeid { get; set; }
        public Nullable<int> SubledgeraccountID { get; set; }
        public int Accgroupid { get; set; }
        public int CurrencyID { get; set; }
        public long Opening_Balance { get; set; }
        public string Address { get; set; }
        public int CountryID { get; set; }
        public Nullable<long> CNIC { get; set; }
        public Nullable<int> Userid { get; set; }
        public Nullable<long> mobileNum { get; set; }
        public string email { get; set; }
        public string BeneficiaryName { get; set; }
        public Nullable<int> SubledgerGroupID { get; set; }
        public string SubledgerGroupName { get; set; }
        public Nullable<double> ClosingBalance { get; set; }
        public Nullable<double> CreditTotal { get; set; }
        public Nullable<double> DebitTotal { get; set; }
    
        public virtual AccGroup AccGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JournalVoucherChild> JournalVoucherChild { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VoucherMaster> VoucherMaster { get; set; }
    }
}
