//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillSundryChild
    {
        public int BillSundryChildID { get; set; }
        public int BillSundryID { get; set; }
        public double Percentage { get; set; }
        public string Symbol { get; set; }
        public double BillSundryAmount { get; set; }
        public int Vouchermasterid { get; set; }
        public Nullable<int> BillSundryNumber { get; set; }
    
        public virtual BillSundry BillSundry { get; set; }
    }
}
