//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itemsnew
    {
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public double ItemPrice { get; set; }
        public Nullable<int> ItemUnitID { get; set; }
        public Nullable<double> ItemMaxDiscount { get; set; }
        public Nullable<double> ItemMinDiscount { get; set; }
        public int ItemGroupID { get; set; }
        public string ItemDescription { get; set; }
    }
}
