//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalVoucherChild
    {
        public int JVchildID { get; set; }
        public int JVMasterID { get; set; }
        public int DrCrID { get; set; }
        public int AccountID { get; set; }
        public double CreditAmount { get; set; }
        public double DebitAmount { get; set; }
        public string ShortNarration { get; set; }
        public Nullable<System.DateTime> JvDate { get; set; }
        public Nullable<double> FcRate { get; set; }
        public Nullable<int> CurrencyID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual DrCr DrCr { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
