//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalVoucherMaster
    {
        public int JvID_VoucherNo { get; set; }
        public System.DateTime VoucherDate { get; set; }
        public string LongNarration { get; set; }
        public int CurrencyID { get; set; }
        public double DebitTotal { get; set; }
        public double CreditTotal { get; set; }
        public string VoucherOtherDetails { get; set; }
        public Nullable<int> VoucherTypeID { get; set; }
        public Nullable<int> jvmasterid { get; set; }
    
        public virtual VoucherType VoucherType { get; set; }
    }
}
