//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialCentreGroup
    {
        public int MaterialGroupID { get; set; }
        public string MaterialGroupName { get; set; }
        public string Alias { get; set; }
        public string PrintName { get; set; }
        public Nullable<int> MaterialGroupUndergroupid { get; set; }
        public string MaterialGroupUndergroupName { get; set; }
    }
}
