//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVCDBLiveEntities : DbContext
    {
        public MVCDBLiveEntities()
            : base("name=MVCDBLiveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AccGroup> AccGroup { get; set; }
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<AccountMainHead> AccountMainHead { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<BillSundry> BillSundry { get; set; }
        public virtual DbSet<BillSundryChild> BillSundryChild { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<DrCr> DrCr { get; set; }
        public virtual DbSet<ItemGroup> ItemGroup { get; set; }
        public virtual DbSet<JournalVoucherChild> JournalVoucherChild { get; set; }
        public virtual DbSet<JournalVoucherMaster> JournalVoucherMaster { get; set; }
        public virtual DbSet<ledgertype> ledgertype { get; set; }
        public virtual DbSet<MaterialCentreGroup> MaterialCentreGroup { get; set; }
        public virtual DbSet<MenuItems> MenuItems { get; set; }
        public virtual DbSet<Purchase> Purchase { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<StockTransferChild> StockTransferChild { get; set; }
        public virtual DbSet<StockTransferMaster> StockTransferMaster { get; set; }
        public virtual DbSet<StudentInfo> StudentInfo { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Units> Units { get; set; }
        public virtual DbSet<UsersMenu> UsersMenu { get; set; }
        public virtual DbSet<VoucherChild> VoucherChild { get; set; }
        public virtual DbSet<VoucherMaster> VoucherMaster { get; set; }
        public virtual DbSet<VoucherType> VoucherType { get; set; }
        public virtual DbSet<Itemsnew> Itemsnew { get; set; }
        public virtual DbSet<treetable> treetable { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<PaymentTypes> PaymentTypes { get; set; }
        public virtual DbSet<Transactions> Transactions { get; set; }
        public virtual DbSet<OrderChild> OrderChild { get; set; }
        public virtual DbSet<ordermaster> ordermaster { get; set; }
        public virtual DbSet<MaterialCentre> MaterialCentre { get; set; }
        public virtual DbSet<Preferences> Preferences { get; set; }
    }
}
