//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordermaster
    {
        public int OrderID { get; set; }
        public int PaymentID { get; set; }
        public int CustomerID { get; set; }
        public int OrderNumber { get; set; }
        public System.DateTime OrderDate { get; set; }
        public decimal FinalTotal { get; set; }
        public string OrderType { get; set; }
        public Nullable<int> SupplierID { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual PaymentTypes PaymentTypes { get; set; }
    }
}
