//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preferences
    {
        public int PreferenceID { get; set; }
        public int Preferencevalue { get; set; }
        public string PreferenceNarration { get; set; }
        public Nullable<int> PreferencetypeID { get; set; }
    }
}
