//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int PurchaseID { get; set; }
        public int PaymentID { get; set; }
        public int SupplierID { get; set; }
        public int PurchaseNumber { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public System.DateTime RecieveDate { get; set; }
        public decimal FinalTotal { get; set; }
        public string OrderType { get; set; }
    
        public virtual PaymentTypes PaymentTypes { get; set; }
    }
}
