//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfo
    {
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public string StudentFatherName { get; set; }
        public int StudentAge { get; set; }
        public string StudentEmail { get; set; }
        public long Fathercnic { get; set; }
        public string FatherOcp { get; set; }
        public string FatherEmail { get; set; }
        public string FatherNumber { get; set; }
        public string Course { get; set; }
        public string Branch { get; set; }
        public System.TimeSpan Timings { get; set; }
    }
}
