//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public int TransactionID { get; set; }
        public int ItemID { get; set; }
        public decimal Quantity { get; set; }
        public System.DateTime TransDate { get; set; }
        public Nullable<int> PayTypeID { get; set; }
        public Nullable<double> ItemPrice { get; set; }
        public Nullable<int> TransType { get; set; }
    
        public virtual PaymentTypes PaymentTypes { get; set; }
    }
}
