//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class treetable
    {
        public int childId { get; set; }
        public int parentId { get; set; }
        public string childName { get; set; }
        public int level { get; set; }
        public string orderSequence { get; set; }
    }
}
