//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersMenu
    {
        public int UserMenuID { get; set; }
        public int UserID { get; set; }
        public int MenuItemID { get; set; }
        public bool AllowUpdate { get; set; }
        public Nullable<bool> AllowRead { get; set; }
        public Nullable<bool> AllowDelete { get; set; }
        public Nullable<bool> AllowInsert { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual MenuItems MenuItems { get; set; }
    }
}
