//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherChild
    {
        public int VoucherchildID { get; set; }
        public int ItemID { get; set; }
        public int Quantity { get; set; }
        public int Unitid { get; set; }
        public double ItemPrice { get; set; }
        public double TotalAmount { get; set; }
        public int BillsundryID { get; set; }
        public int VoucherTypeID { get; set; }
        public int VoucherMasterID { get; set; }
    
        public virtual Units Units { get; set; }
        public virtual Items Items { get; set; }
        public virtual Items Items1 { get; set; }
    }
}
